POST http://localhost:8080/login/social
Content-Type: application/json

{
  "token": "eyJraWQiOiI4NkQ4OEtmIiwiYWxnIjoiUlMyNTYifQ.eyJpc3MiOiJodHRwczovL2FwcGxlaWQuYXBwbGUuY29tIiwiYXVkIjoiY29tLnNvZGFjcmV3LnRlc3Quc2VydmljZSIsImV4cCI6MTYwOTc3NDIwOSwiaWF0IjoxNjA5Njg3ODA5LCJzdWIiOiIwMDE3NzQuYmE4OGQ0ODQ0OTkyNGM3ZmEzYjg2MDE4ZDc2MzJhNWIuMTc1MiIsImNfaGFzaCI6IkRRcmx2N1J4SkE4MFB6UXpvMEUzc2ciLCJlbWFpbCI6Im1pY2hhZWwua2ltQHNvZGFjcmV3LmNvbSIsImVtYWlsX3ZlcmlmaWVkIjoidHJ1ZSIsImF1dGhfdGltZSI6MTYwOTY4NzgwOSwibm9uY2Vfc3VwcG9ydGVkIjp0cnVlfQ.dOW8OM3yK9hD9ArBl9MYn2bbGqZkbORSJpVuL4z9Yv-vT9zIVWFKDBXwkE_PX_e-pNFcrDPY-lQea7O-xAgU-rUVAA7MQ6Jep4JMYyOPfJj7Zhq6LE3YwvHvUvx3NT6ntBYItmk6Vqchhgbb8DYQvqEPxYxIH-94MDLbRUzdOqnCRu8Uvgfrd17y2g4GvQdMPjWpowvafw3_6rVLDLgCxOp3A4hPiamAYQeE30zPM5gFnabKjgGvN3QdHEuwXyxHmI2YdZN6D2ccNNn_eo3kNwn0Ka8I6VgMUFrXP7E0hMbQ0Mjr5ifXfgwCwJ9CbFidVSCrvdBt7_vI-JSk-_IAOg",
  "provider": "APPLE"
}

###
